//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholo_Sikhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int c_id { get; set; }
        public string tittle { get; set; }
        public string teacher { get; set; }
        public string c_description { get; set; }
        public string catagory { get; set; }
        public Nullable<int> price { get; set; }
        public string c_img { get; set; }
        public string Detailcode { get; set; }
        public string learn_des { get; set; }
    }
}
