//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholo_Sikhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int r_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public string email { get; set; }
        public Nullable<int> rating { get; set; }
        public string review1 { get; set; }
        public string reviewdate { get; set; }
        public string username { get; set; }
    }
}
