//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholo_Sikhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionContent
    {
        public int subsec_id { get; set; }
        public Nullable<int> s_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public string subsec_tittle { get; set; }
        public string content_type { get; set; }
        public string content_link { get; set; }
    }
}
