//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cholo_Sikhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int s_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public string tittle { get; set; }
    }
}
